#!/bin/sh

# Exit on non-zero exit code
set -e

# Remove the cache folder, if it still exists
if [ -d /var/cache/motech/motech-default ]; then
    rm -r /var/cache/motech/motech-default
fi

# Remove the log folder, if it still exists
if [ -d /var/log/motech/motech-default ]; then
    rm -r /var/log/motech/motech-default
fi

# Remove the lib folder, if it still exists
if [ -d /var/lib/motech/motech-default ]; then
    rm -r /var/lib/motech/motech-default
fi
