#!/bin/sh

# Exit on non-zero exit code
set -e

# Create the motech user, if he doesn't exist
if [ `grep -c motech-default: /etc/passwd` -eq 0 ]; then
    useradd -r -c "Motech-default user" -d /usr/share/motech/motech-default motech-default
fi

#Create motech.properties
touch /var/lib/motech/motech-default/data/config/motech.properties
echo "motech.app.name=default" > /var/lib/motech/motech-default/data/config/motech.properties

# Make motech the owner of relevant directories
if [ -d /var/log/motech/motech-default ]; then
    chown -R motech-default:motech-default /var/log/motech/motech-default
fi
if [ -d /var/cache/motech/motech-default ]; then
    chown -R motech-default:motech-default /var/cache/motech/motech-default
fi
if [ -d /var/lib/motech/motech-default ]; then
    chown -R motech-default:motech-default /var/lib/motech/motech-default
fi

# Register motech service with udpate-rc.d
update-rc.d motech-default defaults 1>/dev/null

